# Indexing

In [1]:
import pandas as pd

In [12]:
oo = pd.read_csv('../data/olympics.csv',skiprows=4)
oo.head()

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
0,Athens,1896,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold
1,Athens,1896,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100m freestyle,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
3,Athens,1896,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100m freestyle for sailors,M,Gold
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver

## Index

In [3]:
type(oo.index)

pandas.core.indexes.range.RangeIndex

In [4]:
oo.index[100]

100

In [5]:
oo.index[100] = 5

TypeError: Index does not support mutable operations

## set_index()

In [23]:
oo.head()

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
0,"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
1,"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
2,"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
3,"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
4,"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [24]:
oo.set_index('Athlete')

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver
"CHOROPHAS, Efstathios",Athens,1896,Aquatics,Swimming,GRE,Men,1200m freestyle,M,Bronze
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,1200m freestyle,M,Gold
"ANDREOU, Joannis",Athens,1896,Aquatics,Swimming,GRE,Men,1200m freestyle,M,Silver
"CHOROPHAS, Efstathios",Athens,1896,Aquatics,Swimming,GRE,Men,400m freestyle,M,Bronze
"NEUMANN, Paul",Athens,1896,Aquatics,Swimming,AUT,Men,400m freestyle,M,Gold
"PEPANOS, Antonios",Athens,1896,Aquatics,Swimming,GRE,Men,400m freestyle,M,Silver
"LANE, Francis",Athens,1896,Athletics,Athletics,USA,Men,100m,M,Bronze
"SZOKOLYI, Alajos",Athens,1896,Athletics,Athletics,HUN,Men,100m,M,Bronze
"BURKE, Thomas",Athens,1896,Athletics,Athletics,USA,Men,100m,M,Gold
"HOFMANN, Fritz",Athens,1896,Athletics,Athletics,GER,Men,100m,M,Silver
"CURTIS, Thomas",Athens,1896,Athletics,Athletics,USA,Men,110m hurdles,M,Gold
"GOULDING, Grantley",Athens,1896,Athletics,Athletics,GBR,Men,110m hurdles,M,Silver
"LERMUSIAUX, Albin",Athens,1896,Athletics,Athletics,FRA,Men,1500m,M,Bronze
"FLACK, Edwin",Athens,1896,Athletics,Athletics,AUS,Men,1500m,M,Gold
"BLAKE, Arthur",Athens,1896,Athletics,Athletics,USA,Men,1500m,M,Silver
"GMELIN, Charles",Athens,1896,Athletics,Athletics,GBR,Men,400m,M,Bronze
"BURKE, Thomas",Athens,1896,Athletics,Athletics,USA,Men,400m,M,Gold
"JAMISON, Herbert",Athens,1896,Athletics,Athletics,USA,Men,400m,M,Silver
"GOLEMIS, Dimitrios",Athens,1896,Athletics,Athletics,GRE,Men,800m,M,Bronze
"FLACK, Edwin",Athens,1896,Athletics,Athletics,AUS,Men,800m,M,Gold
"DANI, Nandor",Athens,1896,Athletics,Athletics,HUN,Men,800m,M,Silver
"VERSIS, Sotirios",Athens,1896,Athletics,Athletics,GRE,Men,discus throw,M,Bronze
"GARRETT, Robert",Athens,1896,Athletics,Athletics,USA,Men,discus throw,M,Gold
"PARASKEVOPOULOS, Panagiotis",Athens,1896,Athletics,Athletics,GRE,Men,discus throw,M,Silver
"CLARK, Ellery",Athens,1896,Athletics,Athletics,USA,Men,high jump,M,Gold
...,...,...,...,...,...,...,...,...,...
"MUTALIMOV, Marid",Beijing,2008,Wrestling,Wrestling Free.,KAZ,Men,96 - 120kg,M,Bronze
"TAYMAZOV, Artur",Beijing,2008,Wrestling,Wrestling Free.,UZB,Men,96 - 120kg,M,Gold
"AKHMEDOV, Bakhtiyar",Beijing,2008,Wrestling,Wrestling Free.,RUS,Men,96 - 120kg,M,Silver
"AMOYAN, Roman",Beijing,2008,Wrestling,Wrestling Gre-R,ARM,Men,- 55kg,M,Bronze
"PARK, Eun-Chul",Beijing,2008,Wrestling,Wrestling Gre-R,KOR,Men,- 55kg,M,Bronze
"MANKIEV, Nazyr",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,- 55kg,M,Gold
"BAYRAMOV, Rovshan",Beijing,2008,Wrestling,Wrestling Gre-R,AZE,Men,- 55kg,M,Silver
"TENGIZBAYEV, Nurbakyt",Beijing,2008,Wrestling,Wrestling Gre-R,KAZ,Men,55 - 60kg,M,Bronze
"TIUMENBAEV, Ruslan",Beijing,2008,Wrestling,Wrestling Gre-R,KGZ,Men,55 - 60kg,M,Bronze
"ALBIEV, Islam-Beka",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,55 - 60kg,M,Gold
"RAHIMOV, Vitaliy",Beijing,2008,Wrestling,Wrestling Gre-R,AZE,Men,55 - 60kg,M,Silver
"SIAMIONAU, Mikhail",Beijing,2008,Wrestling,Wrestling Gre-R,BLR,Men,60 - 66kg,M,Bronze
"VARDANYAN, Armen",Beijing,2008,Wrestling,Wrestling Gre-R,UKR,Men,60 - 66kg,M,Bronze
"GUENOT, Steeve",Beijing,2008,Wrestling,Wrestling Gre-R,FRA,Men,60 - 66kg,M,Gold
"BEGALIEV, Kanatbek",Beijing,2008,Wrestling,Wrestling Gre-R,KGZ,Men,60 - 66kg,M,Silver
"GUENOT, Christophe",Beijing,2008,Wrestling,Wrestling Gre-R,FRA,Men,66 - 74kg,M,Bronze
"YANAKIEV, Yavor",Beijing,2008,Wrestling,Wrestling Gre-R,BUL,Men,66 - 74kg,M,Bronze
"KVIRKELIA, Manuchar",Beijing,2008,Wrestling,Wrestling Gre-R,GEO,Men,66 - 74kg,M,Gold
"CHANG, Yongxiang",Beijing,2008,Wrestling,Wrestling Gre-R,CHN,Men,66 - 74kg,M,Silver
"AVLUCA, Nazmi",Beijing,2008,Wrestling,Wrestling Gre-R,TUR,Men,74 - 84kg,M,Bronze
"MINGUZZI, Andrea",Beijing,2008,Wrestling,Wrestling Gre-R,ITA,Men,74 - 84kg,M,Gold
"FODOR, Zoltan",Beijing,2008,Wrestling,Wrestling Gre-R,HUN,Men,74 - 84kg,M,Silver
"MAMBETOV, Asset",Beijing,2008,Wrestling,Wrestling Gre-R,KAZ,Men,84 - 96kg,M,Bronze
"WHEELER, Adam",Beijing,2008,Wrestling,Wrestling Gre-R,USA,Men,84 - 96kg,M,Bronze
"KHUSHTOV, Aslanbek",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,84 - 96kg,M,Gold
"ENGLICH, Mirko",Beijing,2008,Wrestling,Wrestling Gre-R,GER,Men,84 - 96kg,M,Silver
"MIZGAITIS, Mindaugas",Beijing,2008,Wrestling,Wrestling Gre-R,LTU,Men,96 - 120kg,M,Bronze
"PATRIKEEV, Yuri",Beijing,2008,Wrestling,Wrestling Gre-R,ARM,Men,96 - 120kg,M,Bronze
"LOPEZ, Mijain",Beijing,2008,Wrestling,Wrestling Gre-R,CUB,Men,96 - 120kg,M,Gold
"BAROEV, Khasan",Beijing,2008,Wrestling,Wrestling Gre-R,RUS,Men,96 - 120kg,M,Silver

In [25]:
oo.head()

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
0,"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
1,"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
2,"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
3,"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
4,"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [26]:
oo.set_index('Athlete',inplace=True)

In [27]:
oo.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [28]:
oo.reset_index(inplace=True)

In [29]:
ath = oo.set_index('Athlete')
ath.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

## reset_index()

In [30]:
ath.head()

,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
Athlete,,,,,,,,,
"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [31]:
ath.reset_index(inplace=True)
ath.head()

,Athlete,City,Edition,Sport,Discipline,NOC,Gender,Event,Event_gender,Medal
0,"HAJOS, Alfred",Athens,1896,Aquatics,Swimming,HUN,Men,100m freestyle,M,Gold
1,"HERSCHMANN, Otto",Athens,1896,Aquatics,Swimming,AUT,Men,100m freestyle,M,Silver
2,"DRIVAS, Dimitrios",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Bronze
3,"MALOKINIS, Ioannis",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Gold
4,"CHASAPIS, Spiridon",Athens,1896,Aquatics,Swimming,GRE,Men,100m freestyle for sailors,M,Silver

In [ ]:
## sort_index()

## loc[...]

## iloc[...]